#!/bin/sh                                                                                                                                  
                                                                                                                                           
DATADIR=/var/lib/icvpn-meta                                                                                                                
                                                                                                                                           
# pull new public keys of peering partners for tinc vpn daemon from https://github.com/freifunk/icvpn                                      
cd /etc/tinc/icvpn
git pull -q

# pull new bgp configs of peering partners from https://github.com/freifunk/icvpn-meta
cd "$DATADIR"
git pull -q

# refresh bgp config v4/v6
sudo -u nobody /opt/icvpn-scripts/mkbgp -4 -f bird -d peers -s "$DATADIR" -x ulm > /etc/bird/bird.d/icvpn.conf
sudo -u nobody /opt/icvpn-scripts/mkbgp -6 -f bird -d peers -s "$DATADIR" -x ulm -t berlin:upstream > /etc/bird/bird6.d/icvpn.conf

# reload bird
birdc configure > /dev/null
birdc6 configure > /dev/null

# refresh DNS config for freifunk zones
##sudo -u nobody /opt/icvpn-scripts/mkdns -f bind -s "$DATADIR" -x ulm > /etc/bind/named.conf.freifunk
# no need; is done in cron.daily

# reload bind9 config
##/etc/init.d/bind9 reload > /dev/null
# no need; is done in cron.daily

