#!/bin/sh
/sbin/ip link set dev $INTERFACE up
/sbin/ip addr add dev $INTERFACE ICVPN_IPV4_ADDR/16 broadcast 10.207.255.255 scope link
/sbin/ip -6 addr add dev $INTERFACE ICVPN_IPV6_ADDR/96 preferred_lft 0

