#!/bin/sh

DATADIR=/var/lib/icvpn-meta

# pull new bgp configs of peering partners from https://github.com/freifunk/icvpn-meta
## cd "$DATADIR"
## git pull -q
# no need; is done in cron.hourly by pulling bgp updates every hour.

# refresh DNS config for freifunk zones
# (but only if config exists)
if [ -f /etc/bind/named.conf.freifunk ]; then
  sudo -u nobody /opt/icvpn-scripts/mkdns -f bind -s "$DATADIR" -x ulm > /etc/bind/named.conf.freifunk
fi

# reload bind9 config
if [ -f /etc/init.d/bind9 ]; then
  /etc/init.d/bind9 reload > /dev/null
fi
